[package]
name = "aedat"
version = "1.2.3"
authors = ["International Centre for Neuromorphic Systems", "Alexandre Marcireau", "Andrew C. Freeman"]
description = "A fast AEDAT4 Rust implementation."
homepage = "https://github.com/andrewcfreeman/aedat-rs"
documentation = "https://github.com/andrewcfreeman/aedat-rs"
repository = "https://github.com/andrewcfreeman/aedat-rs"
readme = "README.md"
license-file = "LICENSE"
edition = "2021"


[profile.release]
lto = true

[lib]
name = "aedat"

[dependencies]
flatbuffers = "2.0.0"
lz4 = "1.23.2"
ndarray = "0.15.3"
roxmltree = "0.14.1"
zstd = "0.9.0"