[package]
name = "aedat"
version = "1.3.1"
authors = ["International Centre for Neuromorphic Systems", "Alexandre Marcireau", "Andrew C. Freeman"]
description = "A fast AEDAT4 Rust implementation. Forked from https://github.com/neuromorphicsystems/aedat, a Rust AEDAT4 decoder for Python projects."
homepage = "https://github.com/andrewcfreeman/aedat-rs"
documentation = "https://github.com/andrewcfreeman/aedat-rs"
repository = "https://github.com/andrewcfreeman/aedat-rs"
readme = "README.md"
license-file = "LICENSE"
edition = "2021"
keywords = ["neuromorphic", "decoding", "davis", "dvs", "aedat"]
categories = ["multimedia::encoding", "science"]


[profile.release]
lto = true

[lib]
name = "aedat"

[dependencies]
flatbuffers = "2.0.0"
lz4 = "1.23.2"
ndarray = "0.15.3"
roxmltree = "0.14.1"
zstd = "0.9.0"
num-traits = "0.2.15"
num-derive = "0.3.3"
thiserror = "1.0.38"
